name: $name
version: $version
main: $group.${name}Plugin
description: $description
author: Hydrolien
website: https://github.com/HydrolienF/WorldCleanerH
api-version: "$apiVersion"
commands:
  clean:
    description: Clean item or block in a selected area.
    usage: /clean <entities|blocks>
    permission: worldcleanerh.clean
dependencies:
  server:
    WorldSelectorH:
      load: BEFORE
      required: true